sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t vikas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vikas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-202142930593"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
